### ISSUE TITLE
Concept Browser

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/cdm-bi#11]
Idea is to browse concepts across data sources (example below is with some fake concepts). 

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/7252105/70039034-1e4d5280-15b1-11ea-90c3-5ac118c49771.png">

Ideas to work on:

- [ ] Allow domain filtering
- [ ] Do not show absolute numbers but magnitude
- [ ] Consider the hierarchical level we want to support in this tool (will depend on the dcs.)
- [ ] Add source filtering

**Comment by joaorafaelalmeida** [comment]
@solventrix Already build this dashboard available at https://dashboards.ehden.eu/tabs/#General%20Concepts
