### ISSUE TITLE
Achilles results version history

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/cdm-bi#12]
To keep track of the growth of the EHDEN network, we need to archive the achilles results, so the number of patients in the network at any given time can be retrieved also when a datasource is updated with new results.

Upon uploading a new achilles results table of an existing data source, store the old achilles results. Some options:
  a) Separate `achilles_results_archive` table to which these records are moved
  b) New field `achilles_datasources.archived` table and numeric primary key in this table

**Comment by MaximMoinat** [comment]
For 'archived' data sources, we should store at least the achilles_results data for analysis_ids 1 and 2 (total number of patients, and stratified by gender). Another option is to add the attributes `n_men` and `n_women` to the `achilles_datasources` table.

**Comment by aspedrosa** [comment]
https://github.com/EHDEN/cdm-bi/issues/17#issuecomment-622330810
