### ISSUE TITLE
Achilles results metadata

### ISSUE THREAD

**Issue by jloliveira** [EHDEN/cdm-bi#17]
We need to define the metadata that should be associated to each Achilles results file.
Some suggestions from the workshop:
- Source name
- Release Date. Date at which DB is available for research for current release
- Last date of patient data
- Achilles generation date
- Achilles version
- CDM version
- Vocab version
- Database type (primary care, secondary care, claims, biobank, registry)
- Location of DB custodian (city, country - geo hierarchy)
- Link (catalogue page)

**Comment by MaximMoinat** [comment]
To keep track of version history of the source, we also need the following two fields in `achilles_datasources`:
* a unique primary key (the source name will not be unique anymore). 
* archived (boolean)

**Comment by aspedrosa** [comment]
DataSource
- [x] Source name. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L47)
- [x] Release Date. Date at which DB is available for research for current release. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L57)
- [x] Database type (primary care, secondary care, claims, biobank, registry). [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L60)
- [x] Location of DB custodian (city, country - geo hierarchy). [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L64)
- [x] Link (catalogue page). [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L72)

Achilles Uploads
- [x] Last date of patient data. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L110)
- [x] Achilles generation date. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L112)
- [x] Achilles version. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L111)
- [x] CDM version. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L113)
- [x] Vocab version. [here](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L114)

The history for the sources are kept on a separate [table](https://github.com/EHDEN/cdm-bi/blob/master/dashboard_viewer/uploader/models.py#L104)
