### ISSUE TITLE
Issue favorite status of dashboard if you are not logged in

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/cdm-bi#7]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/7252105/69007489-9f181780-093e-11ea-9047-bdd49cb92ccf.png">

This is recognized at superset:

https://github.com/apache/incubator-superset/issues/6824

Have not tried the solutions.

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
About this issue, @aspedrosa  already did a PR (https://github.com/apache/incubator-superset/pull/8527) to avoid those messages when you are not logged, but I think this is not merged yet in the master branch.

@aspedrosa did you try to follow the steps in the issue that Peter mentioned to see if it solves the problem?

**Comment by PRijnbeek** [comment]
Awesome. I think there is quite a strict procedure to get these in master, let alone in a new release due to the Apache incubation etc. Hopefully this can be merged into master soon.

**Comment by aspedrosa** [comment]
I think the superset's issue mentioned by Peter is not linked to our problem, although the same toast/alert appears. We have that error because we are accessing superset without an user logged in so he doesn't know which user favorite status he has to get.

**Comment by aspedrosa** [comment]
Fixed with https://github.com/apache/incubator-superset/pull/8527
